### PR TITLE
CPPP-IO Details

### PR DESCRIPTION
**Pull request by stewart**
Adds a new field to robots/devices to show CPPP-IO details. This currently consists of the device route, and a `cURL` command to get JSON data from the server.

Let me know if there's any more features that should be added here.

### CODE REVIEW

**Comment by stewart** [comment]
Screenshot of the current version, there's probably some room for some CSS attention too.
screen shot 2015-07-21 at 3 45 02 pm

**Comment by deadprogram** [comment]
This takes up a lot of screen area, perhaps we can address that?

**Comment by stewart** [comment]
Added some more data, current version should also automatically wrap as well.

screen shot 2015-08-04 at 7 41 01 am

**Comment by deadprogram** [comment]
:diamond_shape_with_a_dot_inside:

**Pull request merged**
